/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PageProgressPageRouteImport } from './routes/page/progressPage'
import { Route as PagePomodoroPageRouteImport } from './routes/page/pomodoroPage'
import { Route as PageLoginRouteImport } from './routes/page/login'
import { Route as PageHomeRouteImport } from './routes/page/home'
import { Route as PageGerenciartarefaPageRouteImport } from './routes/page/gerenciartarefaPage'
import { Route as PageCriarContaRouteImport } from './routes/page/criarConta'

const PageProgressPageRoute = PageProgressPageRouteImport.update({
  id: '/page/progressPage',
  path: '/page/progressPage',
  getParentRoute: () => rootRouteImport,
} as any)
const PagePomodoroPageRoute = PagePomodoroPageRouteImport.update({
  id: '/page/pomodoroPage',
  path: '/page/pomodoroPage',
  getParentRoute: () => rootRouteImport,
} as any)
const PageLoginRoute = PageLoginRouteImport.update({
  id: '/page/login',
  path: '/page/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PageHomeRoute = PageHomeRouteImport.update({
  id: '/page/home',
  path: '/page/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PageGerenciartarefaPageRoute = PageGerenciartarefaPageRouteImport.update({
  id: '/page/gerenciartarefaPage',
  path: '/page/gerenciartarefaPage',
  getParentRoute: () => rootRouteImport,
} as any)
const PageCriarContaRoute = PageCriarContaRouteImport.update({
  id: '/page/criarConta',
  path: '/page/criarConta',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/page/criarConta': typeof PageCriarContaRoute
  '/page/gerenciartarefaPage': typeof PageGerenciartarefaPageRoute
  '/page/home': typeof PageHomeRoute
  '/page/login': typeof PageLoginRoute
  '/page/pomodoroPage': typeof PagePomodoroPageRoute
  '/page/progressPage': typeof PageProgressPageRoute
}
export interface FileRoutesByTo {
  '/page/criarConta': typeof PageCriarContaRoute
  '/page/gerenciartarefaPage': typeof PageGerenciartarefaPageRoute
  '/page/home': typeof PageHomeRoute
  '/page/login': typeof PageLoginRoute
  '/page/pomodoroPage': typeof PagePomodoroPageRoute
  '/page/progressPage': typeof PageProgressPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/page/criarConta': typeof PageCriarContaRoute
  '/page/gerenciartarefaPage': typeof PageGerenciartarefaPageRoute
  '/page/home': typeof PageHomeRoute
  '/page/login': typeof PageLoginRoute
  '/page/pomodoroPage': typeof PagePomodoroPageRoute
  '/page/progressPage': typeof PageProgressPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/page/criarConta'
    | '/page/gerenciartarefaPage'
    | '/page/home'
    | '/page/login'
    | '/page/pomodoroPage'
    | '/page/progressPage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/page/criarConta'
    | '/page/gerenciartarefaPage'
    | '/page/home'
    | '/page/login'
    | '/page/pomodoroPage'
    | '/page/progressPage'
  id:
    | '__root__'
    | '/page/criarConta'
    | '/page/gerenciartarefaPage'
    | '/page/home'
    | '/page/login'
    | '/page/pomodoroPage'
    | '/page/progressPage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageCriarContaRoute: typeof PageCriarContaRoute
  PageGerenciartarefaPageRoute: typeof PageGerenciartarefaPageRoute
  PageHomeRoute: typeof PageHomeRoute
  PageLoginRoute: typeof PageLoginRoute
  PagePomodoroPageRoute: typeof PagePomodoroPageRoute
  PageProgressPageRoute: typeof PageProgressPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/page/progressPage': {
      id: '/page/progressPage'
      path: '/page/progressPage'
      fullPath: '/page/progressPage'
      preLoaderRoute: typeof PageProgressPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/pomodoroPage': {
      id: '/page/pomodoroPage'
      path: '/page/pomodoroPage'
      fullPath: '/page/pomodoroPage'
      preLoaderRoute: typeof PagePomodoroPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/login': {
      id: '/page/login'
      path: '/page/login'
      fullPath: '/page/login'
      preLoaderRoute: typeof PageLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/home': {
      id: '/page/home'
      path: '/page/home'
      fullPath: '/page/home'
      preLoaderRoute: typeof PageHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/gerenciartarefaPage': {
      id: '/page/gerenciartarefaPage'
      path: '/page/gerenciartarefaPage'
      fullPath: '/page/gerenciartarefaPage'
      preLoaderRoute: typeof PageGerenciartarefaPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/criarConta': {
      id: '/page/criarConta'
      path: '/page/criarConta'
      fullPath: '/page/criarConta'
      preLoaderRoute: typeof PageCriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PageCriarContaRoute: PageCriarContaRoute,
  PageGerenciartarefaPageRoute: PageGerenciartarefaPageRoute,
  PageHomeRoute: PageHomeRoute,
  PageLoginRoute: PageLoginRoute,
  PagePomodoroPageRoute: PagePomodoroPageRoute,
  PageProgressPageRoute: PageProgressPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
