/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PageLoginRouteImport } from './routes/page/login'
import { Route as PageCriarContaRouteImport } from './routes/page/criarConta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PageLoginRoute = PageLoginRouteImport.update({
  id: '/page/login',
  path: '/page/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PageCriarContaRoute = PageCriarContaRouteImport.update({
  id: '/page/criarConta',
  path: '/page/criarConta',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/page/criarConta': typeof PageCriarContaRoute
  '/page/login': typeof PageLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/page/criarConta': typeof PageCriarContaRoute
  '/page/login': typeof PageLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/page/criarConta': typeof PageCriarContaRoute
  '/page/login': typeof PageLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/page/criarConta' | '/page/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/page/criarConta' | '/page/login'
  id: '__root__' | '/' | '/page/criarConta' | '/page/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageCriarContaRoute: typeof PageCriarContaRoute
  PageLoginRoute: typeof PageLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/login': {
      id: '/page/login'
      path: '/page/login'
      fullPath: '/page/login'
      preLoaderRoute: typeof PageLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/criarConta': {
      id: '/page/criarConta'
      path: '/page/criarConta'
      fullPath: '/page/criarConta'
      preLoaderRoute: typeof PageCriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageCriarContaRoute: PageCriarContaRoute,
  PageLoginRoute: PageLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
